### ISSUE TITLE
doubts on discriminator

### ISSUE THREAD

**Issue by cyberpunk207777** [z-x-yang/NS-Outpainting#11]
i have some queries regarding working of discriminator in your model, i know that we give the right half of the image to the discriminator but how does the discriminator know when to accept the image generated by the generator when its not generating the exact image but something similar to the real image?

**Comment by z-x-yang** [comment]
It's difficult to generate an image the same as the ground truth. Thus, the discriminator is only responsible for guaranteeing that the prediction should look real and be structurally consistent with the input.

**Comment by cyberpunk207777** [comment]
> It's difficult to generate an image the same as the ground truth. Thus, the discriminator is only responsible for guaranteeing that the prediction should look real and be structurally consistent with the input.

Let's assume that the generator generated some image which is structurally consistent with original image then based on what values will discriminator know that generator generated something similar?

**Comment by z-x-yang** [comment]
I get your question now.

The GAN will bring the data distribution of predictions and the distribution of real images to be closer. This happens on a dataset level or a larger level because we always hope our model can generalize to data out of the training dataset. 

It's good to learn to generate predictions the same as the exact real images because their distribution distance is zero. But, a set of something similar could also have a zero distribution distance w.r.t the real images. Thus, it's reasonable to predict something similar.

Another reason (for why the model can predict something similar) is that it's easy to learn to predict something similar because the high-level hidden feature of something similar should be very close to the feature of the exact real image. This is what auto-encoder and encoder-decoder networks want to do, and they're always good at it.

If you want to know more about these, it's better to read the papers of GAN, Auto-Encoder, and others related.

**Comment by cyberpunk207777** [comment]
Alright! thank you for this
