### ISSUE TITLE
Train promblem~~

### ISSUE THREAD

**Issue by zhangbaijin** [z-x-yang/NS-Outpainting#2]
Hi,yang,thanks for your code! But when i run tarin a problem occured.
Start Exp: 0817/2
Start building model...
build model on gpu tower
tower_0
tower_1
Done.
Start reducing towers on cpu...
Done.
Start training...
Start pretraining G!
Step: 0
2019-12-05 14:54:29.515181: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Attempted to repeat an empty dataset infinitely.
OutOfRangeError (see above for traceback): Attempted to repeat an empty dataset infinitely.
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,128,256,3]], output_types=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]

```
parser = argparse.ArgumentParser(description='Model training.')
# experiment
parser.add_argument('--date', type=str, default='0817')
parser.add_argument('--exp-index', type=int, default=2)
parser.add_argument('--f', action='store_true', default=False)

# gpu
parser.add_argument('--start-gpu', type=int, default=0)
parser.add_argument('--num-gpu', type=int, default=2)

# dataset
parser.add_argument('--trainset-path', type=str, default='./dataset/trainset.tfr')
parser.add_argument('--testset-path', type=str, default='./dataset/testset.tfr')
parser.add_argument('--trainset-length', type=int, default='5041')
parser.add_argument('--testset-length', type=int, default='2000')  # we flip every image in testset
```
it seem like dataset problem,right?.Due to the limit,So i choose 20 Parsi-streetview image for train, I just wanna run it...

**Comment by z-x-yang** [comment]
Very sorry for the late reply.

If you want to train with your images, you need transfer your dataset into TFRecord format firstly. We give an example code here: https://github.com/z-x-yang/NS-Outpainting/blob/master/dataset/build_dataset.py. 

You can also get our dataset  from here: 1) TFRecord format: https://drive.google.com/file/d/1LDRx0W6zo_eCZwN92pGgGZSCrqzB3KZ6/view?usp=sharing or 2) raw: https://drive.google.com/file/d/15rGKgeNHWqjs90An7wpZXJMz-zFaC1q0/view?usp=sharing.

**Comment by zhangbaijin** [comment]
thanks a lot！！

**Comment by zhangbaijin** [comment]
hi,Yang.If I want to do Fig12 experiments, such as a picture 128x256, I block the two sides, input 128x128, and then let them add, how should I modify it, and how to implement multi steps?Thanks  for your time!

**Comment by z-x-yang** [comment]
Sorry for missing your new question due to that I've closed this issue.

If I want to make a two-way extension, I will do one-way extension twice, i.e., flipping or not flipping the input image. After that, I stitch them to a two-way extension. The stitching method is same as the method used in multi-step prediction in our code.

In our released code, I just gave an example about how to stitch the continuous predictions in the one-way extension. However, the two-way extension is easy to realize based on the one-way method.

I will update the two-way method when I am free. If you urgently need, however, I advise you to flip the input image and stitch the extensions from two sides by yourself. Trust me, it’s a very easy job.
