### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by erqiangli** [z-x-yang/NS-Outpainting#3]
Hi,Excuse me,I have a question about the configuration（train.sh and test.sh）,Can you give me an example？
(python train_model.py --trainset-path /path/to/tf-record-trainset --testset-path /path/to/tf-record-testset --checkpoint-path /path/to/checkpoint)
i don't understand the specific meaning of "python train_model.py  --trainset-path /path/to/tf-record-trainset --testset-path /path/to/tf-record-testset"

**Comment by z-x-yang** [comment]
The "trainset-path" and "testset-path" are the TFRecord dataset path in your environment. You can download our dataset (TFRecord format) from here [https://drive.google.com/file/d/1LDRx0W6zo_eCZwN92pGgGZSCrqzB3KZ6/view?usp=sharing](url). Also, you can get our raw dataset (images) from here [https://drive.google.com/file/d/15rGKgeNHWqjs90An7wpZXJMz-zFaC1q0/view?usp=sharing](url).

You can also make a train-test split using your own dataset into TFRecord, and we give an example in here [https://github.com/z-x-yang/NS-Outpainting/blob/master/dataset/build_dataset.py](url).

The "checkpoint-path" is used for loading a pretrain model to start a training process or loading a checkpoint model to resume training from a checkpoint. If you ignore this config, the training will start from a randomly initialised model, which is the default setting in our paper.

If you want to eval the model in our paper, please download our model from here [https://drive.google.com/file/d/1-DLSwNkB93MMKaYVO1rmPP9iJllXDJrg/view?usp=sharing](url).

**Comment by D1vyansh** [comment]
Hi,

Great project!!
I have a small doubt regarding （train.sh and eval.sh）
In both the files you are calling train_model.py and not eval_model.py  for testing

Shouldn't it be like :
python eval_model.py --trainset-path /path/to/tf-record-trainset --testset-path /path/to/tf-record-testset --checkpoint-path /path/to/checkpoint
Instead of :
python train_model.py --trainset-path /path/to/tf-record-trainset --testset-path /path/to/tf-record-testset --checkpoint-path /path/to/checkpoint
For eval.sh
