### ISSUE TITLE
Does the model support outpainting by mask?

### ISSUE THREAD

**Issue by NagabhushanSN95** [z-x-yang/NS-Outpainting#6]
I have an image of size MxM. I have some regions in the boundaries that are missing. The missing pixels are available through a mask. Is it possible to use this model to fill such regions?

**Comment by z-x-yang** [comment]
No, our method can't do with a mask, although I think it's easy to achieve this by slightly modifying the model structure and training process. 

BTW, what you need sounds more like an inpainting method.

**Comment by NagabhushanSN95** [comment]
Hi, thanks for the quick reply. I've attached a sample image below, in which I need to fill the black regions.

![0025](https://user-images.githubusercontent.com/16269001/91676138-79ba6a00-eb5c-11ea-807f-767271850d91.png)

The reason I thought outpainting is more suited of rthis task is that, 
1. The missing pixels are at boundary, so information will be available from only 1 side
2. The size of black regions is considerably large and so it might be difficult for infilling algorithms.

What is your suggestion?
Also, by modifying the model, do you mean I've to give mask along with the input image? Can you please outline what changes to the model and training process would be suitable?

**Comment by z-x-yang** [comment]
In your example, the black region is not too large compared to the visible region. But If much larger, for example, the black region's size is larger than the visible, this will be a challenging and valuable setting. Otherwise, I suppose some latest inpainting methods can handle this well.

The changes are the same as what you thought. Give the mask along with the image, just like what inpainting does.

**Comment by NagabhushanSN95** [comment]
Cool. Thanks a lot
