### ISSUE TITLE
doubts on implementing pre trained model

### ISSUE THREAD

**Issue by SSPlusUltra** [z-x-yang/NS-Outpainting#7]
after downloading your pre trained model i got 3 files now so how do i make the model run? is there a documentation on how to run or do i need to re run all the variable initializations or something like that?excuse me if its a newbie doubt im just getting started in this.

**Comment by z-x-yang** [comment]
Just run `python eval_model.py --checkpoint-path path-to-ckpt/-235500` to evaluate the pre-trained model.

**Comment by SSPlusUltra** [comment]
gave me this error
 InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on path-to-ckpt/-235500: Not found: FindFirstFile failed for: path-to-ckpt : The system cannot find the path specified.

i even had the pretrained model files in same folder as the eval_model.py. btw does it run on tensorflow 1.3+ versions too?

**Comment by z-x-yang** [comment]
......path-to-ckpt is your path to checkpoint folder.------------------ Original ------------------From: SSPlusUltra  <notifications@github.com>Date: Fri,Sep 11,2020 8:42 PMTo: z-x-yang/NS-Outpainting <NS-Outpainting@noreply.github.com>Cc: z-x-yang <zongxinyang1996@gmail.com>, Comment <comment@noreply.github.com>Subject: Re: [z-x-yang/NS-Outpainting] doubts on implementing pre trainedmodel (#7)
gave me this error
InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on path-to-ckpt/-235500: Not found: FindFirstFile failed for: path-to-ckpt : The system cannot find the path specified.
i even had the pretrained model files in same folder as the eval_model.py. btw does it run on tensorflow 1.3+ versions too?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/z-x-yang/NS-Outpainting/issues/7#issuecomment-691071808",
"url": "https://github.com/z-x-yang/NS-Outpainting/issues/7#issuecomment-691071808",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by SSPlusUltra** [comment]
oof thank you it worked.
